name: Maven_Install_Package_Deploy

on:
  push:
    branches: [ master ]

jobs:
    
  maven_install:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
         
    - name: 'Create settings.xml'
      env:
        GITHUB_TOKEN: ${{ secrets.ACTIONSTOKEN }}
      run: |
        touch ~/.m2/settings.xml
        echo '<settings><servers><server><id>github</id><username>$(echo "$GITHUB_REPOSITORY" | awk -F / '{print $1}')</username><password>${{ env.GITHUB_TOKEN }}</password></server></servers></settings>' > ~/.m2/settings.xml
        REPO="github::default::https://maven.pkg.github.com/${GITHUB_REPOSITORY}"
    - name: Maven Install
      run: mvn install
    - name: Maven Package
      run: mvn --file pom.xml package
    - name: Deploy to Github Package Registry
      run: mvn deploy -DaltReleaseDeploymentRepository="${REPO}" -DaltSnapshotDeploymentRepository="${REPO}"  
