name: Maven Install

on:
  push:
    branches: [ master ]

jobs:
    
  Maven_Install:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
         
    - name: 'Create settings.xml'
      env:
        GITHUB_TOKEN: ${{ secrets.ACTIONSTOKEN }}
      run: |
        touch ~/.m2/settings.xml
        echo '<settings><servers><server><id>github</id><username>$(echo "$GITHUB_REPOSITORY" | awk -F / '{print $1}')</username><password>${{ env.GITHUB_TOKEN }}</password></server></servers></settings>' > ~/.m2/settings.xml
    - name: Build
      run: mvn install
