name: Maven_Install_Package_Deploy

on:
  push:
    branches: [ master ]

jobs:
 create_settings_file:
    runs-on: ubuntu-latest

    steps:
    - name: Generate settings.xml for Maven Builds
      uses: whelk-io/maven-settings-xml-action@v14
      with:
        repositories: '[{ "id": "github", "url": "https://maven.pkg.github.com/mwsu-csmp/gg-mwsu" }]'
        servers: '[{ "id": "github", "username": "${{ secrets.USERNAME }}", "password": "${{ secrets.ACTIONSTOKEN }}" }]'       
    
 install:
    runs-on: ubuntu-latest
    needs: create_settings_file
    
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Maven Install
        run: mvn install
      
 deploy:
    runs-on: ubuntu-latest
    needs: install
    
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to Github Package Registry
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONSTOKEN }}
        run:  mvn deploy -DaltReleaseDeploymentRepository="https://maven.pkg.github.com/mwsu-csmp/gg-mwsu" -DaltSnapshotDeploymentRepository="https://maven.pkg.github.com/mwsu-csmp/gg-mwsu"
