name: Maven Install

on:
  push:
    branches: [ master ]

jobs:
    
  Maven_Install:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
 
    - name: 'Create settings.xml'
      uses: whelk-io/maven-settings-xml-action@v4
      env:
        GITHUB_TOKEN: ${{ secrets.ACTIONSTOKEN }}       
      with:
          servers: '[{"id": "github", "password": "${{ env.GITHUB_PASSWORD }}"}]'
    - name: Build
      run: mvn install  
