name: Maven_Install_Package_Deploy

on:
  push:
    branches: [ master ]

jobs:
  create_settings_file:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Generate settings.xml for Maven Builds
      uses: whelk-io/maven-settings-xml-action@v14
      with:
        repositories: '[ {"id": "mwsu-csmp-gg-mwsu", "url": "https://maven.pkg.github.com/mwsu-csmp/gg-mwsu"},{ "id": "mwsu-csmp-gg-game-api", "url": "https://maven.pkg.github.com/mwsu-csmp/gg-game-api", "releases": { "enabled": "true" }, "snapshots": { "enabled": "false" } }]'
        servers: '[{ "id": "mwsu-csmp-gg-game-api", "username": "${{ secrets.ACTIONSUSERNAME }}", "password": "${{ secrets.ACTIONSTOKEN }}" },{ "id": "mwsu-csmp-gg-mwsu", "username": "${{ secrets.ACTIONSUSERNAME }}", "password": "${{ secrets.ACTIONSTOKEN }}" }]' 
    - name: Generate SettingSecurity.xml
      run: echo "<settingsSecurity><master>${secrets.ACTIONSUSERNAME}</master></settingsSecurity>" > /root/.m2/settings-security.xml      
        
  maven_install:
    runs-on: ubuntu-latest
    needs: create_settings_file
    
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
          java-version: 11
    - name: Maven Install
      run: mvn -X install
      
  deploy:
    runs-on: ubuntu-latest
    needs: maven_install
    
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Maven Deploy
        run:  mvn deploy -DaltReleaseDeploymentRepository="https://maven.pkg.github.com/mwsu-csmp/gg-mwsu" -DaltSnapshotDeploymentRepository="https://maven.pkg.github.com/mwsu-csmp/gg-mwsu"
