name: Maven_Install_Package_Deploy

on:
  push:
    branches: [ master ]

jobs:
    
 package:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Maven package
      run: |
          touch ~/.m2/settings.xml
          echo "<settings><activeProfiles><activeProfile>github</activeProfile></activeProfiles><profiles><profile><id>github</id><repositories><repository><id>github</id><name>GitHub mwsu-csmp Apache Maven Packages</name><url>https://maven.pkg.github.com/mwsu-csmp/gg-game-api</url></repository><repository><id>central</id><url>https://repo1.maven.org/maven2</url><releases><enabled>true</enabled></releases><snapshots><enabled>true</enabled></snapshots></repository></repositories></profile></profiles></settings>" > ~/.m2/settings.xml
          REPO="github::default::https://maven.pkg.github.com/${GITHUB_REPOSITORY}"
          mvn package
      
 deploy:
    runs-on: ubuntu-latest
    needs: package
    
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to Github Package Registry
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONSTOKEN }}
        run:  mvn deploy -DaltReleaseDeploymentRepository="${REPO}" -DaltSnapshotDeploymentRepository="${REPO}"
