name: Maven_Install_Package_Deploy

on:
  push:
    branches: [ master ]

jobs:
    
 build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Maven package
      run: mvn --file pom.xml package
      
 deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to Github Package Registry
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONSTOKEN }}
        run: |
          mkdir -p ~/.m2
          echo "<settings><servers><server><id>github</id><username>$(echo "$GITHUB_REPOSITORY" | awk -F / '{print $1}')</username><password>\${env.GITHUB_TOKEN}</password></server></servers></settings>" > ~/.m2/settings.xml
          REPO="github::default::https://maven.pkg.github.com/${GITHUB_REPOSITORY}"
          mvn deploy -DaltReleaseDeploymentRepository="${REPO}" -DaltSnapshotDeploymentRepository="${REPO}"
